### ISSUE TITLE
Warlock soulshards (arena preperation)

### ISSUE THREAD

**Issue by Archevilx** [Proudmoore-Official/Official-Proudmoore-Bugtracker#43]
In arena preperation room its not possible prepare 3 soul shards with soul havrest spell. It always insta reset every server tick in preparition. Its rly big issue in rateds arenas against comps which fast open you.

Its reported too on some twinstar bug report, but cannot find now.

https://www.youtube.com/watch?v=EzDUsQQSDQo here proof from classic 
https://www.youtube.com/watch?v=XzGizMh79_g proof old cata retail

Warlocks on videos can always start with 3 soulshards.

**Comment by RadiantGM** [comment]
Bug confirmed. Soul shards reset while being in the preperation room.

https://www.youtube.com/watch?v=sOH5-qHhWjU

**Comment by Archevilx** [comment]
> Bug confirmed. Soul shards reset while being in the preperation room.
> 
> https://www.youtube.com/watch?v=sOH5-qHhWjU

i tested it many times on ptr no need be tested anymore

**Comment by SylahProudmoore** [comment]
@Archevilx  GMs are the ones who will add this to Github and confirm it.  Please do not raise any tickets on github.  Go through the discord tickets please and the GMs will handle the rest.  Thank you

**Comment by jeniczek** [comment]
TO be tested over PTR. Should be fixed

**Comment by SylahProudmoore** [comment]
@jeniczek partially fixed,  warlock should start with 3 shards on entry,  they can soul harvest in the room and get the shards now

should be revisited

**Comment by Archevilx** [comment]
Can confirm. Its fixed. Working properly. Tested today 15:56 on PTR.
