### ISSUE TITLE
[Vortex Pinnacle] Grand Vizier Ertan - Storm's Edge not doing DMG when cyclones are close to the Boss

### ISSUE THREAD

**Issue by RadiantGM** [Proudmoore-Official/Official-Proudmoore-Bugtracker#49]
The Ability should hit everyone outside the circle of Cyclones ( Inside means between boss and Cyclones ).
As you can see in the video, if the cyclones are close to the boss they do not hit Players standing "outside"
They work fine if the cyclones are on the outer path.

https://www.youtube.com/watch?v=CTQ29kTYY3U

<img width="321" height="127" alt="Image" src="https://github.com/user-attachments/assets/45974a01-7b1a-4760-bdb4-2e36ff7259ca" />

Here on Minute 6 you can see how it was on Cata classic:
https://www.youtube.com/watch?v=ryr_2RwaokY

Here on Minute 0:40 how it was 13 years ago:
https://www.youtube.com/watch?v=ZM5NON3S808

**Comment by SylahProudmoore** [comment]
For clarity

Players that stand outside of the circle of cyclones (the cyclones round the boss) take chain lightning damage = This does work HOWEVER the range is wrong 

Cyclones are called back in , the range of the lightining hitting players is too short and must be increased, the knockback from ertan does work fine

**Comment by SylahProudmoore** [comment]
Fixed

**Comment by ForStateSake** [comment]
Not entirely fixed.

If the player is outside the cyclones circle when the "inner phase" starts, the mechanics work properly and he will get hit by the lightnings.

If the player is inside the cyclones circle instead (which is always the case I guess), the mechanics doesn't work properly and he will not get hit by the lightnings.
